# Generated by Django 3.1.5 on 2021-01-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210107_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.CharField(choices=[('NW', 'Новость'), ('AC', 'Статья')], default='NW', max_length=20),
        ),
    ]
